Verify PGP signature
Signed-off-by: Kaiting Chen <kaitingc@vmware.com>

diff --git a/shared/docker/Dockerfile b/shared/docker/Dockerfile
--- a/shared/docker/Dockerfile
+++ b/shared/docker/Dockerfile
@@ -5,43 +5,57 @@ RUN dpkg-reconfigure locales
 ENV LANG en_US.UTF-8
 ENV LC_ALL en_US.UTF-8
 
-RUN apt-get update; apt-get -y upgrade; apt-get clean
-RUN apt-get install -y git curl wget tar make unzip; apt-get clean
-RUN apt-get install -y realpath; apt-get clean
-RUN apt-get install -y python3; apt-get clean;
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends ca-certificates wget make realpath openssh-client && \
+    apt-get clean
 
-# jq
-RUN curl -L -o "/usr/local/bin/jq" "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64" && \
-    chmod +x "/usr/local/bin/jq"
+# Import stedolan PGP key (jq)
+RUN wget -nv https://raw.githubusercontent.com/stedolan/jq/master/sig/jq-release.key && \
+    gpg --import jq-release.key && \
+    gpg --fingerprint 0x71523402 | grep 'Key fingerprint = 4FD7 01D6 FA9B 3D2D F5AC  935D AF19 040C 7152 3402' && \
+    if [ "$?" != "0" ]; then echo "Invalid PGP key!"; exit 1; fi
 
-# aws CLI
-RUN curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" && \
-    unzip awscli-bundle.zip && \
-    python3 ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws && \
-    rm -rf ./awscli-bundle awscli-bundle.zip
+RUN cd /tmp && \
+    wget -nv https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && \
+    wget -nv https://raw.githubusercontent.com/stedolan/jq/master/sig/v1.5/jq-linux64.asc && \
+    gpg --verify jq-linux64.asc jq-linux64 && \
+    chmod 755 jq-linux64 && \
+    mv jq-linux64 /usr/local/bin/jq
 
-# chruby
-RUN mkdir /tmp/chruby && \
-    cd /tmp && \
-    curl https://codeload.github.com/postmodern/chruby/tar.gz/v0.3.9 | tar -xz && \
-    cd /tmp/chruby-0.3.9 && \
+# Import Postmodern PGP key
+RUN wget -nv https://raw.github.com/postmodern/postmodern.github.io/master/postmodern.asc && \
+    gpg --import postmodern.asc && \
+    gpg --fingerprint 0xB9515E77 | grep 'Key fingerprint = 04B2 F3EA 6541 40BC C7DA  1B57 54C3 D9E9 B951 5E77' && \
+    if [ "$?" != "0" ]; then echo "Invalid PGP key!"; exit 1; fi
+
+ENV RUBY_INSTALL_VERSION=0.6.1 CHRUBY_VERSION=0.3.9 RUBY_VERSION=2.1.7
+
+# Install chruby
+RUN cd /tmp && \
+    wget -nv -O chruby-$CHRUBY_VERSION.tar.gz https://github.com/postmodern/chruby/archive/v$CHRUBY_VERSION.tar.gz && \
+    wget -nv https://raw.github.com/postmodern/chruby/master/pkg/chruby-$CHRUBY_VERSION.tar.gz.asc && \
+    gpg --verify chruby-$CHRUBY_VERSION.tar.gz.asc chruby-$CHRUBY_VERSION.tar.gz && \
+    tar -xzvf chruby-$CHRUBY_VERSION.tar.gz && \
+    cd chruby-$CHRUBY_VERSION/ && \
     sudo ./scripts/setup.sh && \
-    rm -rf /tmp/chruby
+    rm -rf /tmp/chruby-$CHRUBY_VERSION && rm /tmp/*
 
-# ruby-install
-RUN mkdir /tmp/ruby-install && \
-    cd /tmp && \
-    curl https://codeload.github.com/postmodern/ruby-install/tar.gz/v0.6.0 | tar -xz && \
-    cd /tmp/ruby-install-0.6.0 && \
+# Install ruby-install
+RUN cd /tmp && \
+    wget -nv -O ruby-install-$RUBY_INSTALL_VERSION.tar.gz https://github.com/postmodern/ruby-install/archive/v$RUBY_INSTALL_VERSION.tar.gz && \
+    wget -nv https://raw.github.com/postmodern/ruby-install/master/pkg/ruby-install-$RUBY_INSTALL_VERSION.tar.gz.asc && \
+    gpg --verify ruby-install-$RUBY_INSTALL_VERSION.tar.gz.asc ruby-install-$RUBY_INSTALL_VERSION.tar.gz && \
+    tar -xzvf ruby-install-$RUBY_INSTALL_VERSION.tar.gz && \
+    cd ruby-install-$RUBY_INSTALL_VERSION/ && \
     sudo make install && \
-    rm -rf /tmp/ruby-install
+    rm -rf /tmp/ruby-install-$RUBY_INSTALL_VERSION && rm /tmp/*
 
-# ruby
-RUN ruby-install ruby 2.1.7
+# Install Ruby
+RUN ruby-install ruby $RUBY_VERSION -- --disable-install-rdoc
 
-# Bundler
+# Install Bundler
 RUN /bin/bash -l -c "                            \
   source /etc/profile.d/chruby.sh ;              \
-  chruby 2.1.7 ;                                 \
+  chruby $RUBY_VERSION ;                         \
   gem install bundler --no-ri --no-rdoc          \
 "
